### ISSUE TITLE
Metrics exceptions in `quarkus:test`

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-pact#57]
When running in `quarkus:test` mode, some classes needed for pact metrics are missing. The stack traces are harmless, but annoying. We could either fill in the dependency, or disable metrics in that mode.

```
Exception in thread "Thread-226" java.lang.NoClassDefFoundError: org/apache/hc/client5/http/fluent/Request

        at au.com.dius.pact.core.support.Metrics.sendMetrics$lambda-2(Metrics.kt:124)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Instructions for disabling the metrics are:

```
2023-02-08 12:00:02,092 WARN  [au.com.diu.pac.cor.sup.Metrics] (Thread-61) 
            Please note: we are tracking events anonymously to gather important usage statistics like JVM version
            and operating system. To disable tracking, set the 'pact_do_not_track' system property or environment
            variable to 'true'.
```

**Comment by holly-cummins** [comment]
I see the same traces in dev mode, with some server configurations, such as https://github.com/holly-cummins/pact-quarkus-sweater-demo/tree/main/knitter.

**Comment by holly-cummins** [comment]
When reproducing this, make sure to check .profile for 

```
export PACT_DO_NOT_TRACK=true
```
